[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22.12.0"

  [[redirects]]
  from = "/api/aceptacion"
  to = "/.netlify/functions/aceptacion"
  status = 200