import { obterJsonAppsScript } from '../_lib/apps-script.js';

const TIMEOUT_FIREBASE_MS=8000,TIMEOUT_APPS_SCRIPT_MS=20000,ADMIN_CACHE_PREFIX='persoas/cache/administracion/';
const json=(status,body)=>new Response(JSON.stringify(body),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff'}});
const erro=(status,etapa,codigo,mensaxe)=>json(status,{ok:false,etapa,codigo,erro:mensaxe});
async function fetchConLimite(url,options,timeoutMs){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeoutMs);try{return await fetch(url,{...options,redirect:'follow',signal:c.signal});}finally{clearTimeout(t);}}
async function verificarFirebase(idToken,apiKey){const token=String(idToken||'').trim();if(!token)return null;const r=await fetchConLimite(`https://identitytoolkit.googleapis.com/v1/accounts:lookup?key=${apiKey}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({idToken:token})},TIMEOUT_FIREBASE_MS);if(!r.ok)return null;const u=(await r.json())?.users?.[0];return u?.email&&u.emailVerified===true?{uid:String(u.localId||''),email:String(u.email).trim().toLowerCase()}:null;}
async function hashEmail(email){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(String(email||'').trim().toLowerCase()));return Array.from(new Uint8Array(d),b=>b.toString(16).padStart(2,'0')).join('');}
async function verificarAdministracion(env,user){const hash=await hashEmail(user.email);if(env.R2_PRIVADO?.get){const o=await env.R2_PRIVADO.get(`${ADMIN_CACHE_PREFIX}${hash}.json`);if(o){const e=await o.json().catch(()=>null);if(e?.administrador===user.email&&e?.payload?.perfil?.nivel==='Administración')return true;}}try{const r=await chamarAppsScript(env,user,'listarPersoasAdministracion');if(r?.ok&&r?.perfil?.nivel==='Administración'){if(env.R2_PRIVADO?.put){await env.R2_PRIVADO.put(`${ADMIN_CACHE_PREFIX}${hash}.json`,JSON.stringify({savedAt:Date.now(),administrador:user.email,payload:r}),{httpMetadata:{contentType:'application/json; charset=utf-8',cacheControl:'private, no-store'}}).catch(()=>{});}return true;}}catch(e){console.warn('Erro ao validar permisos de administración con Apps Script:',e);}return false;}
async function chamarAppsScript(env,user,accion,datos={}){const {resultado}=await obterJsonAppsScript(env,{token:env.WEB_WRITE_TOKEN,accion,email:user.email,uidFirebase:user.uid,...datos},{timeoutMs:TIMEOUT_APPS_SCRIPT_MS,attemptTimeoutMs:8000});if(!resultado?.ok){const message=resultado?.erro||'Apps Script non puido completar a operación.';const code=resultado?.codigo||(/non autorizado/i.test(message)?'FORBIDDEN':'APPS_SCRIPT_RESULT');throw Object.assign(new Error(message),{code});}return resultado;}
export async function onRequest({request,env}){
 if(request.method!=='POST')return erro(405,'REQUEST','METHOD_NOT_ALLOWED','Método non permitido.');
 if(!env.WEB_WRITE_TOKEN||!env.FIREBASE_API_KEY)return erro(500,'CONFIG','MISSING_CONFIG','O servizo non está configurado correctamente.');
 let body;try{body=await request.json();}catch{return erro(400,'REQUEST','INVALID_JSON','Solicitude non válida.');}
 let user;try{user=await verificarFirebase(body.idToken,env.FIREBASE_API_KEY);}catch{return erro(503,'FIREBASE','FIREBASE_UNAVAILABLE','Non foi posible validar a sesión.');}
 if(!user)return erro(401,'AUTH','INVALID_SESSION','A identificación non é válida ou caducou.');
 try{
  if(!await verificarAdministracion(env,user))return erro(403,'AUTH','FORBIDDEN','Usuario non autorizado para Administración.');
  const accion=String(body.accion||'listar').trim();
  if(accion==='listar'){const r=await chamarAppsScript(env,user,'listarConcertosAdministracionPortal');return json(200,{ok:true,nivel:r.nivel||'Administración',concertos:Array.isArray(r.concertos)?r.concertos:[]});}
  if(accion==='obterXestion'){const idConcerto=String(body.idConcerto||'').trim();if(!idConcerto)return erro(400,'REQUEST','INVALID_DATA','Falta o concerto.');const r=await chamarAppsScript(env,user,'obterXestionConcertoAdministracionPortal',{idConcerto});return json(200,{ok:true,...r});}
  if(accion==='gardarPrograma'){const idConcerto=String(body.idConcerto||'').trim(),programa=Array.isArray(body.programa)?body.programa:[];if(!idConcerto)return erro(400,'REQUEST','INVALID_DATA','Falta o concerto.');if(programa.length>200)return erro(400,'REQUEST','INVALID_DATA','O programa supera o límite permitido.');const limpo=programa.map((i,n)=>({idRepertorio:String(i?.idRepertorio||'').trim(),orde:n+1,solista:String(i?.solista||'').trim().slice(0,300),notas:String(i?.notas||'').trim().slice(0,1000)})).filter(i=>i.idRepertorio);const r=await chamarAppsScript(env,user,'gardarProgramaConcertoAdministracionPortal',{idConcerto,programa:limpo});return json(200,{ok:true,resultado:r.resultado||r});}
  if(accion==='gardarAsistentes'){const idConcerto=String(body.idConcerto||'').trim(),asistentes=Array.isArray(body.asistentes)?body.asistentes.map(v=>String(v||'').trim()).filter(Boolean):[];if(!idConcerto)return erro(400,'REQUEST','INVALID_DATA','Falta o concerto.');if(asistentes.length>200)return erro(400,'REQUEST','INVALID_DATA','Hai demasiados asistentes seleccionados.');const unicos=[...new Set(asistentes)];const r=await chamarAppsScript(env,user,'gardarAsistentesConcertoAdministracionPortal',{idConcerto,asistentes:unicos});return json(200,{ok:true,resultado:r.resultado||r});}
  if(accion==='cambiarData'){const idConcerto=String(body.idConcerto||'').trim(),data=String(body.data||'').trim();if(!idConcerto||!/^\d{4}-\d{2}-\d{2}$/.test(data))return erro(400,'REQUEST','INVALID_DATA','Indica un concerto e unha data válida.');const r=await chamarAppsScript(env,user,'actualizarConcertoAdministracionPortal',{idConcerto,data});return json(200,{ok:true,resultado:r.resultado||r});}
  if(accion==='cambiarEstado'){const idConcerto=String(body.idConcerto||'').trim(),estado=String(body.estado||'').trim();if(!idConcerto||!new Set(['Previsto','Confirmado','Aprazado','Cancelado','Realizado']).has(estado))return erro(400,'REQUEST','INVALID_DATA','Indica un concerto e un estado válido.');const r=await chamarAppsScript(env,user,'actualizarConcertoAdministracionPortal',{idConcerto,estado});return json(200,{ok:true,resultado:r.resultado||r});}
  return erro(400,'REQUEST','ACTION_NOT_ALLOWED','Acción non permitida.');
 }catch(error){const code=error?.code||'UPSTREAM',status=code==='FORBIDDEN'?403:code==='NOT_FOUND'?404:502;return erro(status,'APPS_SCRIPT',code,error?.message||'Non foi posible completar a operación.');}
}
