import { obterJsonAppsScript } from '../_lib/apps-script.js';

const TIMEOUT_FIREBASE_MS = 8_000;
const TIMEOUT_APPS_SCRIPT_MS = 20_000;
const ENSAIOS_CACHE_PREFIX = 'ensaios/cache-v2/usuarios/';
const ADMIN_CACHE_PREFIX = 'persoas/cache/administracion/';

const json = (status, body) => new Response(JSON.stringify(body), {
  status,
  headers: {
    'Content-Type':'application/json; charset=utf-8',
    'Cache-Control':'private, no-store',
    'X-Content-Type-Options':'nosniff'
  }
});
function erro(status, etapa, codigo, mensaxe) { return json(status, { ok:false, etapa, codigo, erro:mensaxe }); }
async function fetchConLimite(url, options, timeoutMs) { const controller=new AbortController(); const timer=setTimeout(()=>controller.abort(),timeoutMs); try{return await fetch(url,{...options,redirect:'follow',signal:controller.signal});}finally{clearTimeout(timer);} }
async function verificarFirebase(idToken, apiKey) { const token=String(idToken||'').trim(); if(!token)return null; const response=await fetchConLimite(`https://identitytoolkit.googleapis.com/v1/accounts:lookup?key=${apiKey}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({idToken:token})},TIMEOUT_FIREBASE_MS); if(!response.ok)return null; const user=(await response.json())?.users?.[0]; if(!user?.email||user.emailVerified!==true)return null; return {uid:String(user.localId||''),email:String(user.email).trim().toLowerCase()}; }
async function hashEmail(email) { const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(String(email||'').trim().toLowerCase())); return Array.from(new Uint8Array(digest),(b)=>b.toString(16).padStart(2,'0')).join(''); }
async function chamarAppsScript(env,user,accion,datos={}) { const {resultado}=await obterJsonAppsScript(env,{token:env.WEB_WRITE_TOKEN,accion,email:user.email,uidFirebase:user.uid,...datos},{timeoutMs:TIMEOUT_APPS_SCRIPT_MS,attemptTimeoutMs:8_000}); if(!resultado?.ok){const message=resultado?.erro||'Apps Script non puido completar a operación.';const code=resultado?.codigo||(/non autorizado/i.test(message)?'FORBIDDEN':'APPS_SCRIPT_RESULT');throw Object.assign(new Error(message),{code});} return resultado; }
async function verificarAdministracionR2(env,user) { if(!env.R2_PRIVADO||typeof env.R2_PRIVADO.get!=='function')return false; const key=`${ADMIN_CACHE_PREFIX}${await hashEmail(user.email)}.json`; const object=await env.R2_PRIVADO.get(key); if(!object)return false; const entry=await object.json().catch(()=>null); return entry?.administrador===user.email&&entry?.payload?.perfil?.nivel==='Administración'; }
async function lerEnsaiosR2(env,user) { if(!env.R2_PRIVADO||typeof env.R2_PRIVADO.get!=='function')return null; const key=`${ENSAIOS_CACHE_PREFIX}${await hashEmail(user.email)}.json`; const object=await env.R2_PRIVADO.get(key); if(!object)return null; const entry=await object.json().catch(()=>null); if(entry?.email!==user.email||entry?.payload?.ok!==true||entry?.payload?.version!==2)return null; return entry.payload; }
async function invalidarCacheEnsaios(env) { if(!env.R2_PRIVADO||typeof env.R2_PRIVADO.list!=='function')return; let cursor; do{const page=await env.R2_PRIVADO.list({prefix:ENSAIOS_CACHE_PREFIX,cursor});const keys=(page.objects||[]).map((item)=>item.key);if(keys.length)await env.R2_PRIVADO.delete(keys);cursor=page.truncated?page.cursor:undefined;}while(cursor); }
function idEnsaio(item={}) { return String(item.idEnsaio||item.Id_Ensaio||item.IdEnsaio||item.id||'').trim(); }
function refEnsaio(item={}) { return String(item.ensaio||item.Ensaio||item.idEnsaio||item.Id_Ensaio||'').trim(); }
function booleano(value) { return value===true||['true','1','si','sí','yes','x'].includes(String(value||'').trim().toLowerCase()); }
function ensaiosAdministracion(result) { const asistencias=Array.isArray(result.asistencias)?result.asistencias:[];const repertorio=Array.isArray(result.ensaiosRepertorio)?result.ensaiosRepertorio:[];const countAsistencias=new Map(),countObras=new Map();asistencias.forEach((item)=>{const id=refEnsaio(item);if(id)countAsistencias.set(id,(countAsistencias.get(id)||0)+1);});repertorio.forEach((item)=>{const id=refEnsaio(item);if(id)countObras.set(id,(countObras.get(id)||0)+1);});return (Array.isArray(result.ensaios)?result.ensaios:[]).map((item)=>{const id=idEnsaio(item);return{idEnsaio:id,data:String(item.data||item.Data||'').slice(0,10),horaInicio:String(item.horaInicio||item.HoraInicio||'').trim(),horaFin:String(item.horaFin||item.HoraFin||'').trim(),lugar:String(item.lugar||item.Lugar||'').trim(),tipoEnsaio:String(item.tipoEnsaio||item.TipoEnsaio||'').trim(),concerto:String(item.concerto||item.Concerto||'').trim(),descricion:String(item.descricion||item.Descricion||'').trim(),observacions:String(item.observacions||item.Observacions||'').trim(),cancelado:booleano(item.cancelado??item.Cancelado),obras:countObras.get(id)||0,asistencias:countAsistencias.get(id)||0};}).filter((item)=>item.idEnsaio).sort((a,b)=>String(b.data).localeCompare(String(a.data))); }
async function listarAdministracion(env,user,adminR2=false) { if(adminR2){const payload=await lerEnsaiosR2(env,user);if(payload)return{nivel:'Administración',ensaios:ensaiosAdministracion(payload),fonte:'R2'};}const result=await chamarAppsScript(env,user,'listarEnsaiosAdministracionPortal');return{nivel:result.nivel||'Xunta Directiva',ensaios:Array.isArray(result.ensaios)?result.ensaios:[],fonte:'SHEET-AUTH'}; }
export async function onRequest(context) { const {request,env}=context;if(request.method!=='POST')return erro(405,'REQUEST','METHOD_NOT_ALLOWED','Método non permitido.');if(!env.WEB_WRITE_TOKEN||!env.FIREBASE_API_KEY)return erro(500,'CONFIG','MISSING_CONFIG','O servizo non está configurado correctamente.');let body;try{body=await request.json();}catch{return erro(400,'REQUEST','INVALID_JSON','Solicitude non válida.');}let user;try{user=await verificarFirebase(body.idToken,env.FIREBASE_API_KEY);}catch{return erro(503,'FIREBASE','FIREBASE_UNAVAILABLE','Non foi posible validar a sesión.');}if(!user)return erro(401,'AUTH','INVALID_SESSION','A identificación non é válida ou caducou.');const accion=String(body.accion||'listar').trim();try{const adminR2=await verificarAdministracionR2(env,user).catch(()=>false);if(accion==='listar'){const result=await listarAdministracion(env,user,adminR2);return json(200,{ok:true,nivel:result.nivel,ensaios:result.ensaios,diagnostico:{fonte:result.fonte}});}if(accion==='cambiarData'){const id=String(body.idEnsaio||'').trim(),data=String(body.data||'').trim();if(!id||!/^\d{4}-\d{2}-\d{2}$/.test(data))return erro(400,'REQUEST','INVALID_DATA','Indica un ensaio e unha data válida.');const result=await chamarAppsScript(env,user,'actualizarEnsaioAdministracionPortal',{idEnsaio:id,data,cancelado:false});await invalidarCacheEnsaios(env);return json(200,{ok:true,resultado:result.resultado||result});}if(accion==='darBaixa'){const id=String(body.idEnsaio||'').trim();if(!id)return erro(400,'REQUEST','INVALID_DATA','Falta o ensaio que se quere dar de baixa.');const result=await chamarAppsScript(env,user,'actualizarEnsaioAdministracionPortal',{idEnsaio:id,cancelado:true});await invalidarCacheEnsaios(env);return json(200,{ok:true,resultado:result.resultado||result});}return erro(400,'REQUEST','ACTION_NOT_ALLOWED','Acción non permitida.');}catch(error){const code=error?.code||'UPSTREAM';const status=code==='FORBIDDEN'?403:code==='NOT_FOUND'?404:502;return erro(status,'APPS_SCRIPT',code,error?.message||'Non foi posible completar a operación.');} }
